version: '3'

services:
#  mautrix-whatsapp:
#    container_name: mautrix-whatsapp
#    image: dock.mau.dev/mautrix/whatsapp:latest
#    restart: always
#    volumes:
#      - /mnt/synapse/whatsapp:/data
#    depends_on:
#      - synapse
    # If you put the service above in the same docker-compose as the homeserver,
    # ignore the parts below. Otherwise, see below for configuring networking.

    # If synapse is running outside of docker, you'll need to expose the port.
    # Note that in most cases you should either run everything inside docker
    # or everything outside docker, rather than mixing docker things with
    # non-docker things.
    #ports:
    #- "127.0.0.1:29319:29318"
    # You'll also probably want this so the bridge can reach Synapse directly
    # using something like `http://host.docker.internal:8008` as the address:
    #extra_hosts:
    #- "host.docker.internal:host-gateway"

  synapse:
#    container_name: synapse
    image: "matrixdotorg/synapse:latest"
    restart: always
    networks:
      - default
      - synapse
    depends_on:
      - postgres
    volumes:
      - /mnt/synapse:/data
    environment:
      VIRTUAL_HOST: "matrix.xxx.com"
      VIRTUAL_PORT: 8008
      SYNAPSE_SERVER_NAME: "matrix.xxx.com"
      SYNAPSE_REPORT_STATS: "yes"
    ports:
#      - "127.0.0.1:8008:8008/tcp"
#      - "127.0.0.1:8448:8448/tcp"

  postgres:
    container_name: postgres
    image: docker.io/postgres:16-alpine
    restart: always
    networks:
      - default
    environment:
      POSTGRES_USER: synapse
      POSTGRES_PASSWORD: synapse
      POSTGRES_DB: synapse
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - /mnt/synapse/postgres:/var/lib/postgresql/data


networks:
  default:
  synapse:
    external: true
